// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WCS.Infrastructure.Persistence;

#nullable disable

namespace WCS.Infrastructure.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    [Migration("20260418030426_CreateWCSDB")]
    partial class CreateWCSDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WCS.Domain.Entities.HistoricalMatch", b =>
                {
                    b.Property<int>("HistoricalMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoricalMatchId"));

                    b.Property<int>("Competition")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("GoalsA")
                        .HasColumnType("integer");

                    b.Property<int>("GoalsB")
                        .HasColumnType("integer");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<int>("TeamAId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamBId")
                        .HasColumnType("integer");

                    b.HasKey("HistoricalMatchId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("Date", "TeamAId", "TeamBId")
                        .IsUnique();

                    b.ToTable("HistoricalMatches", t =>
                        {
                            t.HasCheckConstraint("CK_HistoricalMatch_DifferentTeams", "\"TeamAId\" <> \"TeamBId\"");

                            t.HasCheckConstraint("CK_HistoricalMatch_GoalsA", "\"GoalsA\" >= 0");

                            t.HasCheckConstraint("CK_HistoricalMatch_GoalsB", "\"GoalsB\" >= 0");
                        });
                });

            modelBuilder.Entity("WCS.Domain.Entities.NationalTeam", b =>
                {
                    b.Property<int>("NationalTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NationalTeamId"));

                    b.Property<double>("AttackRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("AvgGoalsConceded")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<double>("AvgGoalsScored")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("Confederation")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentFifaRank")
                        .HasColumnType("integer");

                    b.Property<double>("DefenseRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("OverallRating")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.HasKey("NationalTeamId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NationalTeams", t =>
                        {
                            t.HasCheckConstraint("CK_NationalTeam_AttackRating", "\"AttackRating\" >= 0");

                            t.HasCheckConstraint("CK_NationalTeam_AvgGoalsConceded", "\"AvgGoalsConceded\" >= 0");

                            t.HasCheckConstraint("CK_NationalTeam_AvgGoalsScored", "\"AvgGoalsScored\" >= 0");

                            t.HasCheckConstraint("CK_NationalTeam_Code_Length", "\"Code\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("CK_NationalTeam_CurrentFifaRank", "\"CurrentFifaRank\" > 0");

                            t.HasCheckConstraint("CK_NationalTeam_DefenseRating", "\"DefenseRating\" >= 0");

                            t.HasCheckConstraint("CK_NationalTeam_OverallRating", "\"OverallRating\" >= 0");
                        });
                });

            modelBuilder.Entity("WCS.Domain.Entities.WorldCupMatch", b =>
                {
                    b.Property<int>("WorldCupMatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorldCupMatchId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.Property<int>("TeamAId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamBId")
                        .HasColumnType("integer");

                    b.HasKey("WorldCupMatchId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("Date", "TeamAId", "TeamBId")
                        .IsUnique();

                    b.ToTable("WorldCupMatches", t =>
                        {
                            t.HasCheckConstraint("CK_WorldCupMatch_DifferentTeams", "\"TeamAId\" <> \"TeamBId\"");

                            t.HasCheckConstraint("CK_WorldCupMatch_Round", "\"Round\" BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("WCS.Domain.Entities.WorldCupTeam", b =>
                {
                    b.Property<int>("WorldCupTeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorldCupTeamId"));

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("PositionOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("WorldCupTeamId");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.HasIndex("GroupCode", "PositionOrder")
                        .IsUnique();

                    b.ToTable("WorldCupTeams", t =>
                        {
                            t.HasCheckConstraint("CK_WorldCupTeam_GroupCode", "\"GroupCode\" IN ('A','B','C','D','E','F','G','H','I','J','K','L')");

                            t.HasCheckConstraint("CK_WorldCupTeam_PositionOrder", "\"PositionOrder\" BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("WCS.Domain.Entities.HistoricalMatch", b =>
                {
                    b.HasOne("WCS.Domain.Entities.NationalTeam", "TeamA")
                        .WithMany("TeamAMatches")
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WCS.Domain.Entities.NationalTeam", "TeamB")
                        .WithMany("TeamBMatches")
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("WCS.Domain.Entities.WorldCupMatch", b =>
                {
                    b.HasOne("WCS.Domain.Entities.WorldCupTeam", "TeamA")
                        .WithMany("TeamAMatches")
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WCS.Domain.Entities.WorldCupTeam", "TeamB")
                        .WithMany("TeamBMatches")
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");
                });

            modelBuilder.Entity("WCS.Domain.Entities.WorldCupTeam", b =>
                {
                    b.HasOne("WCS.Domain.Entities.NationalTeam", "Team")
                        .WithOne("WorldCupTeam")
                        .HasForeignKey("WCS.Domain.Entities.WorldCupTeam", "TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WCS.Domain.Entities.NationalTeam", b =>
                {
                    b.Navigation("TeamAMatches");

                    b.Navigation("TeamBMatches");

                    b.Navigation("WorldCupTeam");
                });

            modelBuilder.Entity("WCS.Domain.Entities.WorldCupTeam", b =>
                {
                    b.Navigation("TeamAMatches");

                    b.Navigation("TeamBMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
